"""Optional supervised ML inference for the running API."""

from __future__ import annotations

from pathlib import Path

import joblib


# The model is generated by `python -m ml.train` after downloading the Kaggle data.
MODEL_PATH = Path(__file__).resolve().parents[2] / "models" / "resume_match_ridge.joblib"
_MODEL = None


def load_model():
    """Load the trained model once per process when the artifact exists."""
    global _MODEL
    if _MODEL is None and MODEL_PATH.exists():
        _MODEL = joblib.load(MODEL_PATH)
    return _MODEL


def predict_match_score(resume_text: str, job_description: str) -> float | None:
    """Predict a 0-100 match score; return None when no model is available."""
    model = load_model()
    if model is None:
        return None

    pair_text = f"{resume_text} [JOB] {job_description}".lower()
    prediction = float(model.predict([pair_text])[0])
    return round(max(0.0, min(1.0, prediction)) * 100, 1)
